import os

BUILD = 'debug'
PLATFORM = "local"

global Env 
Env = Environment()




INC = ['inc/', 'inc/lib']
#SRC = Glob('*.cpp') + Glob('service' + '/*.cpp') + Glob('device' + '/*.cpp')
LIBS = ['jsonlib', 'pthread']
LIBPATH = [ ]
CCFLAGS = '-Wall' 
ASFLAGS = ''
LINKFLAGS = ''

if BUILD == 'debug':
    CCFLAGS += ' -g'



if PLATFORM == 'local':

    CC  = 'gcc'
    CXX = 'g++'
    Env['CC'] = CC
    Env['CXX'] = CXX


Env['CCFLAGS'] = CCFLAGS
Env['ASFLAGS'] = ASFLAGS
Env['LINKFLAGS'] = LINKFLAGS
Env['LIBS'] = LIBS
Env['LIBPATH'] = LIBPATH
Env['CPPPATH'] = INC


SRC = Glob("src/*.c") + Glob("src/*.cpp")


Env.SharedLibrary('app', SRC)
Env.Decider('MD5')


#      SConscript(['drivers/SConscript',
#                   'parser/SConscript',
#                   'utilities/SConscript'])